In [3]:
import pandas as pd
import numpy as np
pd.set_option('max_columns',None)

import scipy.stats
from sklearn.preprocessing import StandardScaler

In [4]:
#load the data
train0 = pd.read_csv('df_train.csv')
test0 = pd.read_csv('df_test.csv')

In [5]:
test0

,Unnamed: 0,time,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_pressure,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,8763,2018-01-01 00:00:00,5.000000,level_8,0.0,5.000000,87.000000,71.333333,20.000000,3.000000,0.000000,193.333333,4.000000,176.666667,0.0,1.000000,0.0,sp25,0.0,0,1017.333333,0.0,0.0,0.0,0,800.0,800.000000,1025.666667,800.000000,NaN,284.483333,1030.000000,287.483333,287.483333,801.000000,283.673333,46.333333,287.483333,287.816667,280.816667,287.356667,276.150000,280.380000,286.816667,285.150000,283.150000,279.866667,279.150000
1,8764,2018-01-01 03:00:00,4.666667,level_8,0.0,5.333333,89.000000,78.000000,0.000000,3.666667,0.000000,143.333333,4.666667,266.666667,0.0,0.666667,0.0,sp25,0.0,0,1020.333333,0.0,0.0,0.0,0,800.0,800.333333,1026.666667,800.000000,NaN,282.483333,1030.333333,284.150000,284.150000,721.000000,281.673333,53.666667,284.150000,284.816667,280.483333,284.190000,277.816667,281.010000,283.483333,284.150000,281.150000,279.193333,278.150000
2,8765,2018-01-01 06:00:00,2.333333,level_7,0.0,5.000000,89.000000,89.666667,0.000000,2.333333,6.666667,130.000000,4.000000,263.333333,0.0,0.666667,0.0,sp25,0.0,0,1023.000000,0.0,0.0,0.0,0,800.0,800.000000,1025.333333,800.333333,NaN,280.816667,1030.666667,282.816667,282.816667,800.000000,280.613333,42.000000,282.816667,284.483333,276.483333,283.150000,276.816667,279.196667,281.816667,282.150000,280.483333,276.340000,276.150000
3,8766,2018-01-01 09:00:00,2.666667,level_7,0.0,5.333333,93.333333,82.666667,26.666667,5.666667,6.666667,196.666667,2.333333,86.666667,0.0,1.333333,0.0,sp25,0.0,0,1025.666667,0.0,0.0,0.0,0,800.0,800.000000,1025.000000,800.333333,NaN,281.150000,1032.333333,283.483333,283.483333,801.333333,279.936667,45.000000,283.483333,284.150000,277.150000,283.190000,279.150000,281.740000,282.150000,284.483333,279.150000,275.953333,274.483333
4,8767,2018-01-01 12:00:00,4.000000,level_7,0.0,8.666667,65.333333,64.000000,26.666667,10.666667,0.000000,233.333333,4.666667,283.333333,0.0,1.000000,0.0,sp25,0.0,0,1026.000000,0.0,0.0,0.0,0,800.0,800.333333,1022.333333,800.000000,NaN,287.150000,1032.333333,287.150000,287.150000,801.333333,285.570000,41.000000,287.150000,287.483333,281.150000,286.816667,281.816667,284.116667,286.150000,286.816667,284.483333,280.686667,280.150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,11678,2018-12-31 09:00:00,0.333333,level_9,0.0,2.000000,81.666667,49.666667,80.000000,1.333333,0.000000,70.000000,6.333333,320.000000,0.0,2.000000,0.0,sp24,0.0,0,1029.666667,0.0,0.0,0.0,0,800.0,800.000000,1034.666667,800.000000,NaN,280.816667,1031.666667,279.816667,279.323333,734.333333,280.210000,69.666667,278.816667,279.816667,281.483333,278.140000,270.816667,273.210000,276.483333,276.150000,279.816667,274.910000,271.150000
2916,11679,2018-12-31 12:00:00,0.333333,level_8,0.0,1.333333,61.000000,28.333333,56.666667,1.000000,0.000000,36.666667,2.666667,293.333333,0.0,4.000000,0.0,sp24,0.0,0,1028.666667,0.0,0.0,0.0,0,800.0,800.000000,1034.333333,800.000000,NaN,287.483333,1031.333333,290.816667,290.323333,747.666667,287.280000,32.000000,289.816667,286.483333,287.816667,286.150000,278.150000,278.443333,285.816667,278.816667,287.150000,283.156667,280.483333
2917,11680,2018-12-31 15:00:00,1.000000,level_6,0.0,3.000000,47.000000,26.333333,0.000000,0.666667,0.000000,14.666667,2.666667,233.333333,0.0,4.666667,0.0,sp23,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.000000,1033.000000,800.000000,NaN,290.816667,1030.000000,293.483333,293.483333,800.000000,290.816667,23.666667,293.483333,289.483333,288.816667,288.820000,284.150000,285.073333,288.150000,285.816667,290.816667,287.733333,286.483333
2918,11681,2018-12-31 18:00:00,1.000000,level_6,0.0,2.000000,52.666667,56.666667,0.000000,0.666667,0.000000,19.000000,2.333333,253.333333,0.0,3.333333,0.0,sp23,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.000000,1033.333333,800.000000,NaN,288.816667,1030.333333,286.483333,285.976667,800.000000,288.300000,59.000000,285.483333,285.816667,285.150000,284.473333,280.150000,281.626667,283.150000,282.816667,287.483333,283.813333,282.150000
2919,11682,2018-12-31 21:00:00,1.333333,level_10,0.0,2.333333,61.666667,69.333333,0.000000,1.333333,0.000000,120.000000,4.666667,310.000000,0.0,3.666667,0.0,sp23,0.0,0,1028.000000,0.0,0.0,0.0,0,800.0,800.000000,1034.000000,800.000000,NaN,284.816667,1030.666667,281.150000,280.313333,800.000000,284.423333,79.000000,279.483333,283.816667,276.816667,281.133333,276.150000,276.450000,278.483333,276.816667,283.816667,276.623333,276.483333

In [6]:
train0

,Unnamed: 0,time,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_pressure,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,load_shortfall_3h
0,0,2015-01-01 03:00:00,0.666667,level_5,0.0,0.666667,74.333333,64.000000,0.000000,1.000000,0.000000,223.333333,6.333333,42.666667,0.000000,3.333333,0.0,sp25,0.0,0.0,1036.333333,0.0,0.0,0.0,0.0,800.000000,800.0,1035.000000,800.000000,1002.666667,274.254667,971.333333,269.888000,269.888000,800.000000,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000,6715.666667
1,1,2015-01-01 06:00:00,0.333333,level_10,0.0,1.666667,78.333333,64.666667,0.000000,1.000000,0.000000,221.000000,4.000000,139.000000,0.000000,3.333333,0.0,sp25,0.0,0.0,1037.333333,0.0,0.0,0.0,0.0,800.000000,800.0,1035.666667,800.000000,1004.333333,274.945000,972.666667,271.728333,271.728333,800.000000,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667,4171.666667
2,2,2015-01-01 09:00:00,1.000000,level_9,0.0,1.000000,71.333333,64.333333,0.000000,1.000000,0.000000,214.333333,2.000000,326.000000,0.000000,2.666667,0.0,sp25,0.0,0.0,1038.000000,0.0,0.0,0.0,0.0,800.000000,800.0,1036.000000,800.000000,1005.333333,278.792000,974.000000,278.008667,278.008667,800.000000,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667,4274.666667
3,3,2015-01-01 12:00:00,1.000000,level_8,0.0,1.000000,65.333333,56.333333,0.000000,1.000000,0.000000,199.666667,2.333333,273.000000,0.000000,4.000000,0.0,sp25,0.0,0.0,1037.000000,0.0,0.0,0.0,0.0,800.000000,800.0,1036.000000,800.000000,1009.000000,285.394000,994.666667,284.899552,284.899552,800.000000,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219,5075.666667
4,4,2015-01-01 15:00:00,1.000000,level_7,0.0,1.000000,59.000000,57.000000,2.000000,0.333333,0.000000,185.000000,4.333333,260.000000,0.000000,3.000000,0.0,sp25,0.0,0.0,1035.000000,0.0,0.0,0.0,0.0,800.000000,800.0,1035.333333,800.000000,NaN,285.513719,1035.333333,283.015115,283.015115,800.000000,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437,6620.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,8758,2017-12-31 09:00:00,1.000000,level_6,0.0,2.666667,89.000000,95.666667,56.666667,4.333333,80.000000,226.666667,1.666667,83.666667,45.000000,1.000000,0.0,sp23,0.0,0.0,1021.000000,0.0,0.0,0.0,0.0,727.666667,801.0,1017.666667,769.333333,NaN,285.483333,1024.000000,282.483333,282.483333,802.333333,285.076667,71.333333,282.483333,282.150000,280.816667,281.276667,285.150000,287.573333,280.483333,290.150000,284.816667,279.686667,278.483333,-28.333333
8759,8759,2017-12-31 12:00:00,5.000000,level_6,0.0,2.000000,82.000000,85.000000,26.666667,8.000000,75.000000,220.000000,3.000000,213.333333,85.000000,1.666667,0.0,sp23,0.0,0.0,1019.000000,0.0,0.0,0.0,0.0,762.000000,801.0,1015.333333,803.000000,1021.000000,288.483333,1023.666667,291.816667,291.816667,801.333333,287.673333,40.333333,291.816667,287.816667,283.483333,287.483333,286.483333,288.616667,287.150000,291.150000,287.150000,282.400000,280.150000,2266.666667
8760,8760,2017-12-31 15:00:00,6.333333,level_9,0.4,7.333333,67.666667,71.000000,63.333333,8.333333,33.333333,283.333333,5.333333,256.666667,85.000000,3.666667,0.0,sp22,0.0,0.0,1015.666667,0.0,0.1,0.0,0.0,702.333333,801.0,1017.333333,801.666667,1009.666667,291.483333,1021.666667,290.706333,290.706333,601.000000,290.070000,44.666667,290.706333,290.483333,285.150000,289.816667,283.816667,285.330000,289.150000,286.816667,289.150000,283.956667,281.150000,822.000000
8761,8761,2017-12-31 18:00:00,7.333333,level_8,0.2,7.333333,67.666667,79.000000,63.333333,2.666667,51.666667,220.000000,5.333333,250.000000,56.666667,4.333333,0.0,sp23,0.0,0.0,1015.000000,0.0,0.3,0.0,0.0,500.000000,800.0,1020.333333,802.333333,1020.000000,291.483333,1023.000000,290.483333,290.483333,634.166667,290.070000,45.000000,290.483333,288.150000,283.483333,287.523333,278.816667,281.410000,286.816667,284.150000,289.150000,282.666667,280.816667,-760.000000
8762,8762,2017-12-31 21:00:00,4.333333,level_9,0.0,7.000000,78.666667,68.666667,20.000000,1.666667,33.333333,156.666667,4.333333,253.333333,0.000000,1.666667,0.0,sp25,0.0,0.0,1016.000000,0.0,0.0,0.0,0.0,800.000000,800.0,1023.666667,801.666667,NaN,289.150000,1027.333333,289.483333,289.483333,801.000000,288.140000,50.000000,289.483333,287.816667,282.150000,287.483333,276.816667,281.020000,287.150000,285.150000,287.483333,281.396667,280.483333,2780.666667

## Cleaning the data

In [7]:
#valencia_snow_3h, Bilbao_snow_3h has to change dtype into int(64)
train0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            8763 non-null   int64
 1   time                  8763 non-null   object
 2   Madrid_wind_speed     8763 non-null   float64
 3   Valencia_wind_deg     8763 non-null   object
 4   Bilbao_rain_1h        8763 non-null   float64
 5   Valencia_wind_speed   8763 non-null   float64
 6   Seville_humidity      8763 non-null   float64
 7   Madrid_humidity       8763 non-null   float64
 8   Bilbao_clouds_all     8763 non-null   float64
 9   Bilbao_wind_speed     8763 non-null   float64
 10  Seville_clouds_all    8763 non-null   float64
 11  Bilbao_wind_deg       8763 non-null   float64
 12  Barcelona_wind_speed  8763 non-null   float64
 13  Barcelona_wind_deg    8763 non-null   float64
 14  Madrid_clouds_all     8763 non-null   float64
 15  Seville_wind_speed    8763 non-null   float64
 16  Barcelona_rain_1h     8763 non-null   float64
 17  Seville_pressure      8763 non-null   object
 18  Seville_rain_1h       8763 non-null   float64
 19  Bilbao_snow_3h        8763 non-null   float64
 20  Barcelona_pressure    8763 non-null   float64
 21  Seville_rain_3h       8763 non-null   float64
 22  Madrid_rain_1h        8763 non-null   float64
 23  Barcelona_rain_3h     8763 non-null   float64
 24  Valencia_snow_3h      8763 non-null   float64
 25  Madrid_weather_id     8763 non-null   float64
 26  Barcelona_weather_id  8763 non-null   float64
 27  Bilbao_pressure       8763 non-null   float64
 28  Seville_weather_id    8763 non-null   float64
 29  Valencia_pressure     6695 non-null   float64
 30  Seville_temp_max      8763 non-null   float64
 31  Madrid_pressure       8763 non-null   float64
 32  Valencia_temp_max     8763 non-null   float64
 33  Valencia_temp         8763 non-null   float64
 34  Bilbao_weather_id     8763 non-null   float64
 35  Seville_temp          8763 non-null   float64
 36  Valencia_humidity     8763 non-null   float64
 37  Valencia_temp_min     8763 non-null   float64
 38  Barcelona_temp_max    8763 non-null   float64
 39  Madrid_temp_max       8763 non-null   float64
 40  Barcelona_temp        8763 non-null   float64
 41  Bilbao_temp_min       8763 non-null   float64
 42  Bilbao_temp           8763 non-null   float64
 43  Barcelona_temp_min    8763 non-null   float64
 44  Bilbao_temp_max       8763 non-null   float64
 45  Seville_temp_min      8763 non-null   float64
 46  Madrid_temp           8763 non-null   float64
 47  Madrid_temp_min       8763 non-null   float64
 48  load_shortfall_3h     8763 non-null   float64
dtypes: float64(45), int64(1), object(3)
memory usage: 3.3+ MB

In [8]:
train0.Valencia_snow_3h = train0.Valencia_snow_3h.astype(np.int64)
train0.Bilbao_snow_3h = train0.Bilbao_snow_3h.astype(np.int64)

In [9]:
train0.isna().sum()

Unnamed: 0                 0
time                       0
Madrid_wind_speed          0
Valencia_wind_deg          0
Bilbao_rain_1h             0
Valencia_wind_speed        0
Seville_humidity           0
Madrid_humidity            0
Bilbao_clouds_all          0
Bilbao_wind_speed          0
Seville_clouds_all         0
Bilbao_wind_deg            0
Barcelona_wind_speed       0
Barcelona_wind_deg         0
Madrid_clouds_all          0
Seville_wind_speed         0
Barcelona_rain_1h          0
Seville_pressure           0
Seville_rain_1h            0
Bilbao_snow_3h             0
Barcelona_pressure         0
Seville_rain_3h            0
Madrid_rain_1h             0
Barcelona_rain_3h          0
Valencia_snow_3h           0
Madrid_weather_id          0
Barcelona_weather_id       0
Bilbao_pressure            0
Seville_weather_id         0
Valencia_pressure       2068
Seville_temp_max           0
Madrid_pressure            0
Valencia_temp_max          0
Valencia_temp              0
Bilbao_weather_id          0
Seville_temp               0
Valencia_humidity          0
Valencia_temp_min          0
Barcelona_temp_max         0
Madrid_temp_max            0
Barcelona_temp             0
Bilbao_temp_min            0
Bilbao_temp                0
Barcelona_temp_min         0
Bilbao_temp_max            0
Seville_temp_min           0
Madrid_temp                0
Madrid_temp_min            0
load_shortfall_3h          0
dtype: int64

In [10]:
#combine train and test sets for the sake of mean imputation
target = train0['load_shortfall_3h']
test_time = test0['time']

train1 = train0.drop(['time', 'load_shortfall_3h'], axis=1)
test1 = test0.drop(['time'], axis=1)

data1= pd.concat([train1, test1], axis=0).reset_index(drop=True)

In [11]:
data1

,Unnamed: 0,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_pressure,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0,0.666667,level_5,0.0,0.666667,74.333333,64.000000,0.000000,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,sp25,0.0,0,1036.333333,0.0,0.0,0.0,0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.000000,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,1,0.333333,level_10,0.0,1.666667,78.333333,64.666667,0.000000,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,sp25,0.0,0,1037.333333,0.0,0.0,0.0,0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.000000,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,2,1.000000,level_9,0.0,1.000000,71.333333,64.333333,0.000000,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,sp25,0.0,0,1038.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.000000,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,3,1.000000,level_8,0.0,1.000000,65.333333,56.333333,0.000000,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,sp25,0.0,0,1037.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.000000,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,4,1.000000,level_7,0.0,1.000000,59.000000,57.000000,2.000000,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,sp25,0.0,0,1035.000000,0.0,0.0,0.0,0,800.0,800.0,1035.333333,800.0,NaN,285.513719,1035.333333,283.015115,283.015115,800.000000,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11678,11678,0.333333,level_9,0.0,2.000000,81.666667,49.666667,80.000000,1.333333,0.0,70.000000,6.333333,320.000000,0.0,2.000000,0.0,sp24,0.0,0,1029.666667,0.0,0.0,0.0,0,800.0,800.0,1034.666667,800.0,NaN,280.816667,1031.666667,279.816667,279.323333,734.333333,280.210000,69.666667,278.816667,279.816667,281.483333,278.140000,270.816667,273.210000,276.483333,276.150000,279.816667,274.910000,271.150000
11679,11679,0.333333,level_8,0.0,1.333333,61.000000,28.333333,56.666667,1.000000,0.0,36.666667,2.666667,293.333333,0.0,4.000000,0.0,sp24,0.0,0,1028.666667,0.0,0.0,0.0,0,800.0,800.0,1034.333333,800.0,NaN,287.483333,1031.333333,290.816667,290.323333,747.666667,287.280000,32.000000,289.816667,286.483333,287.816667,286.150000,278.150000,278.443333,285.816667,278.816667,287.150000,283.156667,280.483333
11680,11680,1.000000,level_6,0.0,3.000000,47.000000,26.333333,0.000000,0.666667,0.0,14.666667,2.666667,233.333333,0.0,4.666667,0.0,sp23,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.0,1033.000000,800.0,NaN,290.816667,1030.000000,293.483333,293.483333,800.000000,290.816667,23.666667,293.483333,289.483333,288.816667,288.820000,284.150000,285.073333,288.150000,285.816667,290.816667,287.733333,286.483333
11681,11681,1.000000,level_6,0.0,2.000000,52.666667,56.666667,0.000000,0.666667,0.0,19.000000,2.333333,253.333333,0.0,3.333333,0.0,sp23,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.0,1033.333333,800.0,NaN,288.816667,1030.333333,286.483333,285.976667,800.000000,288.300000,59.000000,285.483333,285.816667,285.150000,284.473333,280.150000,281.626667,283.150000,282.816667,287.483333,283.813333,282.150000
11682,11682,1.333333,level_10,0.0,2.333333,61.666667,69.333333,0.000000,1.333333,0.0,120.000000,4.666667,310.000000,0.0,3.666667,0.0,sp23,0.0,0,1028.000000,0.0,0.0,0.0,0,800.0,800.0,1034.000000,800.0,NaN,284.816667,1030.666667,281.150000,280.313333,800.000000,284.423333,79.000000,279.483333,283.816667,276.816667,281.133333,276.150000,276.450000,278.483333,276.816667,283.816667,276.623333,276.483333

## Ensure proper datatypes

In [12]:
data1.select_dtypes(np.number)

,Unnamed: 0,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0,0.666667,0.0,0.666667,74.333333,64.000000,0.000000,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,0.0,0,1036.333333,0.0,0.0,0.0,0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.000000,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,1,0.333333,0.0,1.666667,78.333333,64.666667,0.000000,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,0.0,0,1037.333333,0.0,0.0,0.0,0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.000000,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,2,1.000000,0.0,1.000000,71.333333,64.333333,0.000000,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,0.0,0,1038.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.000000,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,3,1.000000,0.0,1.000000,65.333333,56.333333,0.000000,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,0.0,0,1037.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.000000,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,4,1.000000,0.0,1.000000,59.000000,57.000000,2.000000,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,0.0,0,1035.000000,0.0,0.0,0.0,0,800.0,800.0,1035.333333,800.0,NaN,285.513719,1035.333333,283.015115,283.015115,800.000000,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11678,11678,0.333333,0.0,2.000000,81.666667,49.666667,80.000000,1.333333,0.0,70.000000,6.333333,320.000000,0.0,2.000000,0.0,0.0,0,1029.666667,0.0,0.0,0.0,0,800.0,800.0,1034.666667,800.0,NaN,280.816667,1031.666667,279.816667,279.323333,734.333333,280.210000,69.666667,278.816667,279.816667,281.483333,278.140000,270.816667,273.210000,276.483333,276.150000,279.816667,274.910000,271.150000
11679,11679,0.333333,0.0,1.333333,61.000000,28.333333,56.666667,1.000000,0.0,36.666667,2.666667,293.333333,0.0,4.000000,0.0,0.0,0,1028.666667,0.0,0.0,0.0,0,800.0,800.0,1034.333333,800.0,NaN,287.483333,1031.333333,290.816667,290.323333,747.666667,287.280000,32.000000,289.816667,286.483333,287.816667,286.150000,278.150000,278.443333,285.816667,278.816667,287.150000,283.156667,280.483333
11680,11680,1.000000,0.0,3.000000,47.000000,26.333333,0.000000,0.666667,0.0,14.666667,2.666667,233.333333,0.0,4.666667,0.0,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.0,1033.000000,800.0,NaN,290.816667,1030.000000,293.483333,293.483333,800.000000,290.816667,23.666667,293.483333,289.483333,288.816667,288.820000,284.150000,285.073333,288.150000,285.816667,290.816667,287.733333,286.483333
11681,11681,1.000000,0.0,2.000000,52.666667,56.666667,0.000000,0.666667,0.0,19.000000,2.333333,253.333333,0.0,3.333333,0.0,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.0,1033.333333,800.0,NaN,288.816667,1030.333333,286.483333,285.976667,800.000000,288.300000,59.000000,285.483333,285.816667,285.150000,284.473333,280.150000,281.626667,283.150000,282.816667,287.483333,283.813333,282.150000
11682,11682,1.333333,0.0,2.333333,61.666667,69.333333,0.000000,1.333333,0.0,120.000000,4.666667,310.000000,0.0,3.666667,0.0,0.0,0,1028.000000,0.0,0.0,0.0,0,800.0,800.0,1034.000000,800.0,NaN,284.816667,1030.666667,281.150000,280.313333,800.000000,284.423333,79.000000,279.483333,283.816667,276.816667,281.133333,276.150000,276.450000,278.483333,276.816667,283.816667,276.623333,276.483333

In [13]:
data2 = data1.copy()
data2

,Unnamed: 0,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_pressure,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0,0.666667,level_5,0.0,0.666667,74.333333,64.000000,0.000000,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,sp25,0.0,0,1036.333333,0.0,0.0,0.0,0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.000000,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,1,0.333333,level_10,0.0,1.666667,78.333333,64.666667,0.000000,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,sp25,0.0,0,1037.333333,0.0,0.0,0.0,0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.000000,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,2,1.000000,level_9,0.0,1.000000,71.333333,64.333333,0.000000,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,sp25,0.0,0,1038.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.000000,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,3,1.000000,level_8,0.0,1.000000,65.333333,56.333333,0.000000,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,sp25,0.0,0,1037.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.000000,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,4,1.000000,level_7,0.0,1.000000,59.000000,57.000000,2.000000,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,sp25,0.0,0,1035.000000,0.0,0.0,0.0,0,800.0,800.0,1035.333333,800.0,NaN,285.513719,1035.333333,283.015115,283.015115,800.000000,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11678,11678,0.333333,level_9,0.0,2.000000,81.666667,49.666667,80.000000,1.333333,0.0,70.000000,6.333333,320.000000,0.0,2.000000,0.0,sp24,0.0,0,1029.666667,0.0,0.0,0.0,0,800.0,800.0,1034.666667,800.0,NaN,280.816667,1031.666667,279.816667,279.323333,734.333333,280.210000,69.666667,278.816667,279.816667,281.483333,278.140000,270.816667,273.210000,276.483333,276.150000,279.816667,274.910000,271.150000
11679,11679,0.333333,level_8,0.0,1.333333,61.000000,28.333333,56.666667,1.000000,0.0,36.666667,2.666667,293.333333,0.0,4.000000,0.0,sp24,0.0,0,1028.666667,0.0,0.0,0.0,0,800.0,800.0,1034.333333,800.0,NaN,287.483333,1031.333333,290.816667,290.323333,747.666667,287.280000,32.000000,289.816667,286.483333,287.816667,286.150000,278.150000,278.443333,285.816667,278.816667,287.150000,283.156667,280.483333
11680,11680,1.000000,level_6,0.0,3.000000,47.000000,26.333333,0.000000,0.666667,0.0,14.666667,2.666667,233.333333,0.0,4.666667,0.0,sp23,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.0,1033.000000,800.0,NaN,290.816667,1030.000000,293.483333,293.483333,800.000000,290.816667,23.666667,293.483333,289.483333,288.816667,288.820000,284.150000,285.073333,288.150000,285.816667,290.816667,287.733333,286.483333
11681,11681,1.000000,level_6,0.0,2.000000,52.666667,56.666667,0.000000,0.666667,0.0,19.000000,2.333333,253.333333,0.0,3.333333,0.0,sp23,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.0,1033.333333,800.0,NaN,288.816667,1030.333333,286.483333,285.976667,800.000000,288.300000,59.000000,285.483333,285.816667,285.150000,284.473333,280.150000,281.626667,283.150000,282.816667,287.483333,283.813333,282.150000
11682,11682,1.333333,level_10,0.0,2.333333,61.666667,69.333333,0.000000,1.333333,0.0,120.000000,4.666667,310.000000,0.0,3.666667,0.0,sp23,0.0,0,1028.000000,0.0,0.0,0.0,0,800.0,800.0,1034.000000,800.0,NaN,284.816667,1030.666667,281.150000,280.313333,800.000000,284.423333,79.000000,279.483333,283.816667,276.816667,281.133333,276.150000,276.450000,278.483333,276.816667,283.816667,276.623333,276.483333

# Impute Missing Values

In [14]:
from sklearn.neighbors import KNeighborsRegressor
#Create a function that will help you fill in missing values using KNeighbours instead of mean

In [15]:
def knn_impute(df, na_target_column):
    df = df.copy()
    
    numeric_df= df.select_dtypes(np.number)
    non_na_columns = numeric_df.loc[: , numeric_df.isna().sum() == 0].columns
    
    y_train = numeric_df.loc[numeric_df[na_target_column].isna() == False, na_target_column]
    X_train =  numeric_df.loc[numeric_df[na_target_column].isna() == False, non_na_columns]
    X_test = numeric_df.loc[numeric_df[na_target_column].isna() == True, non_na_columns]
    
    knn= KNeighborsRegressor()
    knn.fit(X_train, y_train)
    
    y_pred = knn.predict(X_test)
    
    df.loc[df[na_target_column].isna() == True, na_target_column] = y_pred
    
    return df

In [16]:
data2 = knn_impute(data2, 'Valencia_pressure')

In [17]:
#check missing values in DataFrame

data2.isna().sum()

Unnamed: 0              0
Madrid_wind_speed       0
Valencia_wind_deg       0
Bilbao_rain_1h          0
Valencia_wind_speed     0
Seville_humidity        0
Madrid_humidity         0
Bilbao_clouds_all       0
Bilbao_wind_speed       0
Seville_clouds_all      0
Bilbao_wind_deg         0
Barcelona_wind_speed    0
Barcelona_wind_deg      0
Madrid_clouds_all       0
Seville_wind_speed      0
Barcelona_rain_1h       0
Seville_pressure        0
Seville_rain_1h         0
Bilbao_snow_3h          0
Barcelona_pressure      0
Seville_rain_3h         0
Madrid_rain_1h          0
Barcelona_rain_3h       0
Valencia_snow_3h        0
Madrid_weather_id       0
Barcelona_weather_id    0
Bilbao_pressure         0
Seville_weather_id      0
Valencia_pressure       0
Seville_temp_max        0
Madrid_pressure         0
Valencia_temp_max       0
Valencia_temp           0
Bilbao_weather_id       0
Seville_temp            0
Valencia_humidity       0
Valencia_temp_min       0
Barcelona_temp_max      0
Madrid_temp_max         0
Barcelona_temp          0
Bilbao_temp_min         0
Bilbao_temp             0
Barcelona_temp_min      0
Bilbao_temp_max         0
Seville_temp_min        0
Madrid_temp             0
Madrid_temp_min         0
dtype: int64

In [18]:
data3 = data2.copy()

# Feature Transformations

In [19]:
skew_df = pd.DataFrame(data3.select_dtypes(np.number).columns, columns = ['feature'])
skew_df['skew'] = skew_df['feature'].apply(lambda feature: scipy.stats.skew(data3[feature]))
skew_df['absolute_skew'] = skew_df['skew'].apply(abs)
skew_df['skewed'] = skew_df['absolute_skew'].apply(lambda x: True if x >= 0.5 else False)
skew_df

                 feature       skew  absolute_skew  skewed
0             Unnamed: 0   0.000000       0.000000   False
1      Madrid_wind_speed   1.452605       1.452605    True
2         Bilbao_rain_1h   5.693807       5.693807    True
3    Valencia_wind_speed   3.115952       3.115952    True
4       Seville_humidity  -0.365986       0.365986   False
5        Madrid_humidity  -0.076580       0.076580   False
6      Bilbao_clouds_all  -0.068326       0.068326   False
7      Bilbao_wind_speed   1.602316       1.602316    True
8     Seville_clouds_all   1.764878       1.764878    True
9        Bilbao_wind_deg   0.246816       0.246816   False
10  Barcelona_wind_speed   1.072279       1.072279    True
11    Barcelona_wind_deg  -0.140319       0.140319   False
12     Madrid_clouds_all   1.158337       1.158337    True
13    Seville_wind_speed   1.213281       1.213281    True
14     Barcelona_rain_1h   9.831929       9.831929    True
15       Seville_rain_1h   7.534976       7.534976    True
16        Bilbao_snow_3h  31.942074      31.942074    True
17    Barcelona_pressure  66.940457      66.940457    True
18       Seville_rain_3h  22.346298      22.346298    True
19        Madrid_rain_1h   6.445686       6.445686    True
20     Barcelona_rain_3h  14.667040      14.667040    True
21      Valencia_snow_3h   0.000000       0.000000   False
22     Madrid_weather_id  -2.908680       2.908680    True
23  Barcelona_weather_id  -2.595084       2.595084    True
24       Bilbao_pressure  -0.977406       0.977406    True
25    Seville_weather_id  -3.230084       3.230084    True
26     Valencia_pressure  -2.031430       2.031430    True
27      Seville_temp_max   0.122147       0.122147   False
28       Madrid_pressure  -2.139974       2.139974    True
29     Valencia_temp_max   0.068268       0.068268   False
30         Valencia_temp   0.045854       0.045854   False
31     Bilbao_weather_id  -1.316921       1.316921    True
32          Seville_temp   0.219814       0.219814   False
33     Valencia_humidity  -0.292609       0.292609   False
34     Valencia_temp_min   0.069517       0.069517   False
35    Barcelona_temp_max   0.241511       0.241511   False
36       Madrid_temp_max   0.321134       0.321134   False
37        Barcelona_temp   0.105566       0.105566   False
38       Bilbao_temp_min   0.202514       0.202514   False
39           Bilbao_temp   0.270515       0.270515   False
40    Barcelona_temp_min   0.002288       0.002288   False
41       Bilbao_temp_max   0.331264       0.331264   False
42      Seville_temp_min   0.305553       0.305553   False
43           Madrid_temp   0.325073       0.325073   False
44       Madrid_temp_min   0.296367       0.296367   False

In [20]:
#correct the skewed columns by applying a log function
# apply the log (x + 1) to catter for 0 values
for column in skew_df.query('skewed == True')['feature'].values:
    data3[column] = np.log1p(data3[column])

In [21]:
#check again for skewness
skew_df = pd.DataFrame(data3.select_dtypes(np.number).columns, columns = ['feature'])
skew_df['skew'] = skew_df['feature'].apply(lambda feature: scipy.stats.skew(data3[feature]))
skew_df['absolute_skew'] = skew_df['skew'].apply(abs)
skew_df['skewed'] = skew_df['absolute_skew'].apply(lambda x: True if x >= 0.5 else False)
skew_df

                 feature       skew  absolute_skew  skewed
0             Unnamed: 0   0.000000       0.000000   False
1      Madrid_wind_speed   0.398125       0.398125   False
2         Bilbao_rain_1h   3.559209       3.559209    True
3    Valencia_wind_speed   0.390219       0.390219   False
4       Seville_humidity  -0.365986       0.365986   False
5        Madrid_humidity  -0.076580       0.076580   False
6      Bilbao_clouds_all  -0.068326       0.068326   False
7      Bilbao_wind_speed   0.347658       0.347658   False
8     Seville_clouds_all   0.760690       0.760690    True
9        Bilbao_wind_deg   0.246816       0.246816   False
10  Barcelona_wind_speed  -0.093514       0.093514   False
11    Barcelona_wind_deg  -0.140319       0.140319   False
12     Madrid_clouds_all   0.297812       0.297812   False
13    Seville_wind_speed   0.118263       0.118263   False
14     Barcelona_rain_1h   5.526634       5.526634    True
15       Seville_rain_1h   5.242669       5.242669    True
16        Bilbao_snow_3h  19.972290      19.972290    True
17    Barcelona_pressure  27.079994      27.079994    True
18       Seville_rain_3h  22.100271      22.100271    True
19        Madrid_rain_1h   4.480607       4.480607    True
20     Barcelona_rain_3h  14.478975      14.478975    True
21      Valencia_snow_3h   0.000000       0.000000   False
22     Madrid_weather_id  -3.376530       3.376530    True
23  Barcelona_weather_id  -3.020579       3.020579    True
24       Bilbao_pressure  -1.019465       1.019465    True
25    Seville_weather_id  -3.734970       3.734970    True
26     Valencia_pressure  -2.056073       2.056073    True
27      Seville_temp_max   0.122147       0.122147   False
28       Madrid_pressure  -2.174552       2.174552    True
29     Valencia_temp_max   0.068268       0.068268   False
30         Valencia_temp   0.045854       0.045854   False
31     Bilbao_weather_id  -1.583682       1.583682    True
32          Seville_temp   0.219814       0.219814   False
33     Valencia_humidity  -0.292609       0.292609   False
34     Valencia_temp_min   0.069517       0.069517   False
35    Barcelona_temp_max   0.241511       0.241511   False
36       Madrid_temp_max   0.321134       0.321134   False
37        Barcelona_temp   0.105566       0.105566   False
38       Bilbao_temp_min   0.202514       0.202514   False
39           Bilbao_temp   0.270515       0.270515   False
40    Barcelona_temp_min   0.002288       0.002288   False
41       Bilbao_temp_max   0.331264       0.331264   False
42      Seville_temp_min   0.305553       0.305553   False
43           Madrid_temp   0.325073       0.325073   False
44       Madrid_temp_min   0.296367       0.296367   False

# Encoding

In [22]:
data4 = data3.copy()

In [23]:
data4.drop('Unnamed: 0',axis=1, inplace = True)
data4

,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_pressure,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0.510826,level_5,0.0,0.510826,74.333333,64.000000,0.000000,0.693147,0.0,223.333333,1.992430,42.666667,0.0,1.466337,0.0,sp25,0.0,0.0,6.944409,0.0,0.0,0.0,0,6.685861,6.685861,6.943122,6.685861,6.911415,274.254667,6.879699,269.888000,269.888000,6.685861,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,0.287682,level_10,0.0,0.980829,78.333333,64.666667,0.000000,0.693147,0.0,221.000000,1.609438,139.000000,0.0,1.466337,0.0,sp25,0.0,0.0,6.945372,0.0,0.0,0.0,0,6.685861,6.685861,6.943766,6.685861,6.913074,274.945000,6.881069,271.728333,271.728333,6.685861,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,0.693147,level_9,0.0,0.693147,71.333333,64.333333,0.000000,0.693147,0.0,214.333333,1.098612,326.000000,0.0,1.299283,0.0,sp25,0.0,0.0,6.946014,0.0,0.0,0.0,0,6.685861,6.685861,6.944087,6.685861,6.914069,278.792000,6.882437,278.008667,278.008667,6.685861,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,0.693147,level_8,0.0,0.693147,65.333333,56.333333,0.000000,0.693147,0.0,199.666667,1.203973,273.000000,0.0,1.609438,0.0,sp25,0.0,0.0,6.945051,0.0,0.0,0.0,0,6.685861,6.685861,6.944087,6.685861,6.917706,285.394000,6.903413,284.899552,284.899552,6.685861,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,0.693147,level_7,0.0,0.693147,59.000000,57.000000,2.000000,0.287682,0.0,185.000000,1.673976,260.000000,0.0,1.386294,0.0,sp25,0.0,0.0,6.943122,0.0,0.0,0.0,0,6.685861,6.685861,6.943444,6.685861,6.923432,285.513719,6.943444,283.015115,283.015115,6.685861,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11678,0.287682,level_9,0.0,1.098612,81.666667,49.666667,80.000000,0.847298,0.0,70.000000,1.992430,320.000000,0.0,1.098612,0.0,sp24,0.0,0.0,6.937961,0.0,0.0,0.0,0,6.685861,6.685861,6.942801,6.685861,6.929125,280.816667,6.939900,279.816667,279.323333,6.600324,280.210000,69.666667,278.816667,279.816667,281.483333,278.140000,270.816667,273.210000,276.483333,276.150000,279.816667,274.910000,271.150000
11679,0.287682,level_8,0.0,0.847298,61.000000,28.333333,56.666667,0.693147,0.0,36.666667,1.299283,293.333333,0.0,1.609438,0.0,sp24,0.0,0.0,6.936990,0.0,0.0,0.0,0,6.685861,6.685861,6.942479,6.685861,6.929256,287.483333,6.939577,290.816667,290.323333,6.618294,287.280000,32.000000,289.816667,286.483333,287.816667,286.150000,278.150000,278.443333,285.816667,278.816667,287.150000,283.156667,280.483333
11680,0.693147,level_6,0.0,1.386294,47.000000,26.333333,0.000000,0.510826,0.0,14.666667,1.299283,233.333333,0.0,1.734601,0.0,sp23,0.0,0.0,6.935370,0.0,0.0,0.0,0,6.685861,6.685861,6.941190,6.685861,6.929256,290.816667,6.938284,293.483333,293.483333,6.685861,290.816667,23.666667,293.483333,289.483333,288.816667,288.820000,284.150000,285.073333,288.150000,285.816667,290.816667,287.733333,286.483333
11681,0.693147,level_6,0.0,1.098612,52.666667,56.666667,0.000000,0.510826,0.0,19.000000,1.203973,253.333333,0.0,1.466337,0.0,sp23,0.0,0.0,6.935370,0.0,0.0,0.0,0,6.685861,6.685861,6.941512,6.685861,6.929256,288.816667,6.938608,286.483333,285.976667,6.685861,288.300000,59.000000,285.483333,285.816667,285.150000,284.473333,280.150000,281.626667,283.150000,282.816667,287.483333,283.813333,282.150000
11682,0.847298,level_10,0.0,1.203973,61.666667,69.333333,0.000000,0.847298,0.0,120.000000,1.734601,310.000000,0.0,1.540445,0.0,sp23,0.0,0.0,6.936343,0.0,0.0,0.0,0,6.685861,6.685861,6.942157,6.685861,6.929778,284.816667,6.938931,281.150000,280.313333,6.685861,284.423333,79.000000,279.483333,283.816667,276.816667,281.133333,276.150000,276.450000,278.483333,276.816667,283.816667,276.623333,276.483333

In [24]:
#dummy code the whole data frame
data4 = pd.get_dummies(data4)

# Scaling

In [25]:
data5 = data4.copy()

In [26]:
scaler = StandardScaler()
scaler.fit(data5)

data5 = pd.DataFrame(scaler.transform(data5), index=data5.index, columns=data5.columns)

In [27]:
data5

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,Valencia_wind_deg_level_1,Valencia_wind_deg_level_10,Valencia_wind_deg_level_2,Valencia_wind_deg_level_3,Valencia_wind_deg_level_4,Valencia_wind_deg_level_5,Valencia_wind_deg_level_6,Valencia_wind_deg_level_7,Valencia_wind_deg_level_8,Valencia_wind_deg_level_9,Seville_pressure_sp1,Seville_pressure_sp10,Seville_pressure_sp11,Seville_pressure_sp12,Seville_pressure_sp13,Seville_pressure_sp14,Seville_pressure_sp15,Seville_pressure_sp16,Seville_pressure_sp17,Seville_pressure_sp18,Seville_pressure_sp19,Seville_pressure_sp2,Seville_pressure_sp20,Seville_pressure_sp21,Seville_pressure_sp22,Seville_pressure_sp23,Seville_pressure_sp24,Seville_pressure_sp25,Seville_pressure_sp3,Seville_pressure_sp4,Seville_pressure_sp5,Seville_pressure_sp6,Seville_pressure_sp7,Seville_pressure_sp8,Seville_pressure_sp9
0,-1.257907,-0.445987,-1.208327,0.475220,0.216411,-1.355623,-0.494626,-0.742149,0.628254,1.661214,-1.634751,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.063439,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.777042,0.337435,-1.290378,-2.436246,-2.011975,-2.886015,-2.920074,0.609908,-2.364999,0.555399,-2.904614,-1.385995,-2.443090,-1.325760,-2.326231,-2.539139,-1.189628,-2.719042,-2.090559,-2.413444,-2.322453,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,2.990481,-0.335816,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
1,-1.723994,-0.445987,-0.327175,0.655251,0.243745,-1.355623,-0.494626,-0.742149,0.605152,0.830926,-0.548582,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.068709,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.843893,0.337435,-1.088138,-2.358930,-1.944021,-2.638690,-2.662955,0.609908,-2.278690,0.310302,-2.641834,-1.448368,-2.396325,-1.393323,-2.172083,-2.385183,-1.260241,-2.568659,-2.005709,-2.364982,-2.273112,-0.340218,3.001856,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
2,-0.877085,-0.445987,-0.866515,0.340197,0.230078,-1.355623,-0.494626,-0.742149,0.539146,-0.276493,1.559864,-0.924886,0.345499,-0.27126,-0.26046,-0.058091,0.072219,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.877303,0.337435,-0.966954,-1.928076,-1.876159,-1.794668,-1.785511,0.609908,-1.797721,0.030192,-1.745068,-1.307130,-1.737382,-1.240334,-1.480942,-1.694903,-1.100346,-1.894402,-1.532866,-1.682125,-1.577857,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,3.162427,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
3,-0.877085,-0.445987,-0.866515,0.070151,-0.097931,-1.355623,-0.494626,-0.742149,0.393934,-0.048082,0.962283,-0.924886,1.009356,-0.27126,-0.26046,-0.058091,0.066953,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.877303,0.337435,-0.523642,-1.188669,-0.836012,-0.868594,-0.822765,0.609908,-0.972309,-0.582550,-0.761123,-1.051406,-0.779866,-0.963333,-0.573360,-0.788451,-0.810840,-1.008992,-0.721399,-0.689860,-0.567576,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,2.939292,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
4,-0.877085,-0.445987,-0.866515,-0.214898,-0.070596,-1.293210,-1.285015,-0.742149,0.248721,0.970839,0.815706,-0.924886,0.531739,-0.27126,-0.26046,-0.058091,0.056405,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.810473,0.337435,0.174320,-1.175261,1.149142,-1.121846,-1.086045,0.609908,-0.957341,-0.354960,-1.030201,-0.943742,-0.906691,-0.846712,-0.407382,-0.622679,-0.688954,-0.847068,-0.706684,-0.821288,-0.701390,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,2.954273,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11678,-1.723994,-0.445987,-0.106358,0.805277,-0.371271,1.140879,-0.194134,-0.742149,-0.889878,1.661214,1.492213,-0.924886,-0.084017,-0.27126,-0.26046,-0.058091,0.028178,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.743600,0.337435,0.868309,-1.701319,0.973377,-1.551689,-1.601835,0.131316,-1.620436,0.240274,-1.629695,-1.551324,-0.822797,-1.755834,-2.106603,-1.964594,-1.898306,-1.731642,-1.406921,-1.444353,-1.749269,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,3.162427,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,4.917202,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
11679,-1.723994,-0.445987,-0.577516,-0.124882,-1.245962,0.412733,-0.494626,-0.742149,-1.219907,0.158541,1.191544,-0.924886,1.009356,-0.27126,-0.26046,-0.058091,0.022869,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.710147,0.337435,0.884217,-0.954669,0.957367,-0.073385,-0.064992,0.231860,-0.736513,-1.738005,-0.059011,-0.630012,-0.162673,-0.556777,-1.016920,-1.187925,-0.438083,-1.345074,-0.505565,-0.553608,-0.722846,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,2.939292,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,4.917202,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
11680,-0.877085,-0.445987,0.432982,-0.754990,-1.327964,-1.355623,-0.850032,-0.742149,-1.437725,0.158541,0.515037,-0.924886,1.277256,-0.27126,-0.26046,-0.058091,0.014010,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.576229,0.337435,0.884217,-0.581345,0.893277,0.284992,0.376502,0.609908,-0.294343,-2.175678,0.464550,-0.215421,-0.058442,-0.157092,-0.125362,-0.203980,-0.073027,-0.330332,-0.054887,-0.059269,-0.063003,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,2.977818,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
11681,-0.877085,-0.445987,-0.106358,-0.499946,-0.084264,-1.355623,-0.850032,-0.742149,-1.394822,-0.048082,0.740539,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.014010,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.609725,0.337435,0.884217,-0.805339,0.909308,-0.655747,-0.672278,0.609908,-0.608988,-0.319946,-0.677765,-0.722143,-0.440620,-0.807766,-0.719734,-0.715493,-0.855289,-0.765221,-0.464594,-0.482679,-0.539556,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,2.977818,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
11682,-0.555106,-0.445987,0.091170,-0.094877,0.435084,-1.355623,-0.194134,-0.742149,-0.394835,1.102267,1.379462,-0.924886,0.861683,-0.27126,-0.26046,-0.058091,0.019327,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.676684,0.337435,0.947826,-1.253329,0.925333,-1.372501,-1.463519,0.609908,-1.093666,0.730468,-1.534502,-0.998537,-1.309204,-1.307747,-1.314106,-1.483752,-1.585401,-1.635000,-0.915273,-1.259291,-1.162742,-0.340218,3.001856,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571

# Target Transformation

In [28]:
#target.hist()

# Split Data

In [29]:
train_final = data5.loc[:train0.index.max(), :].copy()
test_final = data5.loc[train0.index.max() +1:, :].reset_index(drop=True).copy()

In [30]:
train_final

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,Valencia_wind_deg_level_1,Valencia_wind_deg_level_10,Valencia_wind_deg_level_2,Valencia_wind_deg_level_3,Valencia_wind_deg_level_4,Valencia_wind_deg_level_5,Valencia_wind_deg_level_6,Valencia_wind_deg_level_7,Valencia_wind_deg_level_8,Valencia_wind_deg_level_9,Seville_pressure_sp1,Seville_pressure_sp10,Seville_pressure_sp11,Seville_pressure_sp12,Seville_pressure_sp13,Seville_pressure_sp14,Seville_pressure_sp15,Seville_pressure_sp16,Seville_pressure_sp17,Seville_pressure_sp18,Seville_pressure_sp19,Seville_pressure_sp2,Seville_pressure_sp20,Seville_pressure_sp21,Seville_pressure_sp22,Seville_pressure_sp23,Seville_pressure_sp24,Seville_pressure_sp25,Seville_pressure_sp3,Seville_pressure_sp4,Seville_pressure_sp5,Seville_pressure_sp6,Seville_pressure_sp7,Seville_pressure_sp8,Seville_pressure_sp9
0,-1.257907,-0.445987,-1.208327,0.475220,0.216411,-1.355623,-0.494626,-0.742149,0.628254,1.661214,-1.634751,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.063439,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.777042,0.337435,-1.290378,-2.436246,-2.011975,-2.886015,-2.920074,0.609908,-2.364999,0.555399,-2.904614,-1.385995,-2.443090,-1.325760,-2.326231,-2.539139,-1.189628,-2.719042,-2.090559,-2.413444,-2.322453,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,2.990481,-0.335816,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
1,-1.723994,-0.445987,-0.327175,0.655251,0.243745,-1.355623,-0.494626,-0.742149,0.605152,0.830926,-0.548582,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.068709,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.843893,0.337435,-1.088138,-2.358930,-1.944021,-2.638690,-2.662955,0.609908,-2.278690,0.310302,-2.641834,-1.448368,-2.396325,-1.393323,-2.172083,-2.385183,-1.260241,-2.568659,-2.005709,-2.364982,-2.273112,-0.340218,3.001856,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
2,-0.877085,-0.445987,-0.866515,0.340197,0.230078,-1.355623,-0.494626,-0.742149,0.539146,-0.276493,1.559864,-0.924886,0.345499,-0.27126,-0.26046,-0.058091,0.072219,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.877303,0.337435,-0.966954,-1.928076,-1.876159,-1.794668,-1.785511,0.609908,-1.797721,0.030192,-1.745068,-1.307130,-1.737382,-1.240334,-1.480942,-1.694903,-1.100346,-1.894402,-1.532866,-1.682125,-1.577857,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,3.162427,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
3,-0.877085,-0.445987,-0.866515,0.070151,-0.097931,-1.355623,-0.494626,-0.742149,0.393934,-0.048082,0.962283,-0.924886,1.009356,-0.27126,-0.26046,-0.058091,0.066953,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.877303,0.337435,-0.523642,-1.188669,-0.836012,-0.868594,-0.822765,0.609908,-0.972309,-0.582550,-0.761123,-1.051406,-0.779866,-0.963333,-0.573360,-0.788451,-0.810840,-1.008992,-0.721399,-0.689860,-0.567576,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,2.939292,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
4,-0.877085,-0.445987,-0.866515,-0.214898,-0.070596,-1.293210,-1.285015,-0.742149,0.248721,0.970839,0.815706,-0.924886,0.531739,-0.27126,-0.26046,-0.058091,0.056405,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.810473,0.337435,0.174320,-1.175261,1.149142,-1.121846,-1.086045,0.609908,-0.957341,-0.354960,-1.030201,-0.943742,-0.906691,-0.846712,-0.407382,-0.622679,-0.688954,-0.847068,-0.706684,-0.821288,-0.701390,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,2.954273,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,-0.877085,-0.445987,0.269855,1.135333,1.514780,0.412733,1.417344,1.839351,0.661257,-0.531835,-1.172471,1.153938,-0.951876,-0.27126,-0.26046,-0.058091,-0.018004,-0.057911,-0.294383,-0.096201,0.0,-0.375764,0.382990,0.023635,-0.003259,0.334208,-1.178664,0.603843,-1.193312,-1.160342,0.626183,-1.011984,0.327809,-1.106133,-1.228865,-0.892284,-1.286291,0.023231,0.167041,-1.272496,0.297842,-0.792360,-0.928412,-0.942794,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,2.977818,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
8759,1.417624,-0.445987,-0.106358,0.820279,1.077435,-0.523455,2.437332,1.801922,0.595251,0.347173,0.289535,1.493676,-0.336121,-0.27126,-0.26046,-0.058091,-0.028717,-0.057911,-0.294383,-0.096201,0.0,-0.022045,0.382990,-0.214676,0.370061,0.916025,-0.842672,0.587713,0.061006,0.143647,0.619214,-0.687337,-1.300333,0.226568,-0.445749,-0.614337,-0.357184,0.221356,0.321880,-0.229479,0.442805,-0.505565,-0.635337,-0.759504,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,2.977818,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
8760,1.836772,1.272264,1.809011,0.175169,0.503419,0.620775,2.508225,1.335128,1.222305,1.343393,0.778123,1.493676,0.861683,-0.27126,-0.26046,-0.058091,-0.046619,-0.057911,0.524827,-0.096201,0.0,-0.647616,0.382990,-0.010376,0.355576,-0.443213,-0.506680,0.490827,-0.088213,-0.011482,-0.988085,-0.387695,-1.072743,0.068024,-0.077224,-0.440620,-0.007896,-0.174893,-0.165888,0.083426,-0.185369,-0.259741,-0.467197,-0.649530,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,3.162427,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,4.764218,-0.194059,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
8761,2.103781,0.485068,1.809011,0.175169,0.831428,0.620775,0.686939,1.586476,0.595251,1.343393,0.702955,1.276669,1.147495,-0.27126,-0.26046,-0.058091,-0.050206,-0.057911,1.960691,-0.096201,0.0,-3.253740,0.374397,0.295323,0.362821,0.796700,-0.506680,0.555439,-0.118182,-0.042638,-0.688017,-0.387695,-1.055236,0.036182,-0.399683,-0.614337,-0.351196,-0.917858,-0.747648,-0.281630,-0.571937,-0.259741,-0.606534,-0.686188,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,2.939292,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
8762,1.171606,-0.445987,1.732479,0.670254,0.407750,-0.731497,0.066164,1.335128,-0.031803,0.970839,0.740539,-0.924886,-0.336121,-0.27126,-0.26046,-0.058091,-0.044826,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.633937,0.355576,0.493887,-0.768007,0.764848,-0.252573,-0.182351,0.616889,-0.628992,-0.792633,-0.106607,-0.445749,-0.753310,-0.357184,-1.215044,-0.805527,-0.229479,-0.426974,-0.464594,-0.743710,-0.722846,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,3.162427,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571

In [31]:
test_final

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,Valencia_wind_deg_level_1,Valencia_wind_deg_level_10,Valencia_wind_deg_level_2,Valencia_wind_deg_level_3,Valencia_wind_deg_level_4,Valencia_wind_deg_level_5,Valencia_wind_deg_level_6,Valencia_wind_deg_level_7,Valencia_wind_deg_level_8,Valencia_wind_deg_level_9,Seville_pressure_sp1,Seville_pressure_sp10,Seville_pressure_sp11,Seville_pressure_sp12,Seville_pressure_sp13,Seville_pressure_sp14,Seville_pressure_sp15,Seville_pressure_sp16,Seville_pressure_sp17,Seville_pressure_sp18,Seville_pressure_sp19,Seville_pressure_sp2,Seville_pressure_sp20,Seville_pressure_sp21,Seville_pressure_sp22,Seville_pressure_sp23,Seville_pressure_sp24,Seville_pressure_sp25,Seville_pressure_sp3,Seville_pressure_sp4,Seville_pressure_sp5,Seville_pressure_sp6,Seville_pressure_sp7,Seville_pressure_sp8,Seville_pressure_sp9
0,1.417624,-0.445987,1.193139,1.045318,0.517086,-0.731497,0.856554,-0.742149,0.331228,0.830926,-0.123886,-0.924886,-0.951876,-0.27126,-0.26046,-0.058091,-0.037661,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.836578,0.337435,0.477928,-1.290662,0.893277,-0.521356,-0.461777,0.616889,-1.187435,-0.985209,-0.392186,-0.445749,-0.892284,-0.376145,-1.314106,-0.900508,-0.281630,-0.426974,-0.997214,-0.908970,-0.869478,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,2.939292,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
1,1.298235,-0.445987,1.294503,1.135333,0.790427,-1.355623,1.157046,-0.742149,-0.163815,1.102267,0.890874,-0.924886,-1.342118,-0.27126,-0.26046,-0.058091,-0.021573,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.377263,0.937750,0.337435,0.374147,-1.514656,0.909308,-0.969327,-0.927487,0.028932,-1.437484,-0.600057,-0.868151,-0.860340,-0.927027,-0.850180,-1.066451,-0.807011,-0.803138,-0.571937,-1.243039,-0.981698,-0.979452,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,2.939292,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
2,0.189894,-0.445987,1.193139,1.135333,1.268774,-1.355623,0.501147,0.454409,-0.295826,0.830926,0.853290,-0.924886,-1.342118,-0.27126,-0.26046,-0.058091,-0.007312,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.802832,0.341066,0.414074,-1.701319,0.925333,-1.148515,-1.113771,0.609908,-1.570010,-1.212798,-1.058537,-0.906405,-1.343948,-1.005862,-1.215044,-1.076124,-1.063893,-0.861863,-1.324980,-1.289895,-1.199400,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,2.954273,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
3,0.388971,-0.445987,1.294503,1.330366,0.981766,-0.523455,1.852327,0.454409,0.364231,-0.048082,-1.138646,-0.924886,-0.621932,-0.27126,-0.26046,-0.058091,0.006912,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.769075,0.341066,0.270278,-1.663986,1.005381,-1.058921,-1.020629,0.619214,-1.654609,-1.055236,-0.963344,-0.952471,-1.274461,-0.999874,-0.868327,-0.698673,-1.011742,-0.523616,-1.488863,-1.331660,-1.382690,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,2.954273,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
4,1.036803,-0.445987,2.087266,0.070151,0.216411,-0.523455,2.943208,-0.742149,0.727262,1.102267,1.078792,-0.924886,-0.951876,-0.27126,-0.26046,-0.058091,0.008687,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.377263,0.498624,0.337435,0.254291,-0.992002,1.005381,-0.566153,-0.508348,0.619214,-0.950305,-1.265319,-0.439783,-0.491815,-0.857540,-0.456981,-0.472079,-0.345957,-0.385932,-0.185369,-0.833331,-0.820399,-0.759504,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,2.954273,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,-0.203368,5.048967,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,-1.723994,-0.445987,-0.106358,0.805277,-0.371271,1.140879,-0.194134,-0.742149,-0.889878,1.661214,1.492213,-0.924886,-0.084017,-0.27126,-0.26046,-0.058091,0.028178,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.743600,0.337435,0.868309,-1.701319,0.973377,-1.551689,-1.601835,0.131316,-1.620436,0.240274,-1.629695,-1.551324,-0.822797,-1.755834,-2.106603,-1.964594,-1.898306,-1.731642,-1.406921,-1.444353,-1.749269,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,3.162427,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,4.917202,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
2916,-1.723994,-0.445987,-0.577516,-0.124882,-1.245962,0.412733,-0.494626,-0.742149,-1.219907,0.158541,1.191544,-0.924886,1.009356,-0.27126,-0.26046,-0.058091,0.022869,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.710147,0.337435,0.884217,-0.954669,0.957367,-0.073385,-0.064992,0.231860,-0.736513,-1.738005,-0.059011,-0.630012,-0.162673,-0.556777,-1.016920,-1.187925,-0.438083,-1.345074,-0.505565,-0.553608,-0.722846,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,2.939292,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,-0.194059,4.917202,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
2917,-0.877085,-0.445987,0.432982,-0.754990,-1.327964,-1.355623,-0.850032,-0.742149,-1.437725,0.158541,0.515037,-0.924886,1.277256,-0.27126,-0.26046,-0.058091,0.014010,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.576229,0.337435,0.884217,-0.581345,0.893277,0.284992,0.376502,0.609908,-0.294343,-2.175678,0.464550,-0.215421,-0.058442,-0.157092,-0.125362,-0.203980,-0.073027,-0.330332,-0.054887,-0.059269,-0.063003,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,2.977818,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
2918,-0.877085,-0.445987,-0.106358,-0.499946,-0.084264,-1.355623,-0.850032,-0.742149,-1.394822,-0.048082,0.740539,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.014010,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.609725,0.337435,0.884217,-0.805339,0.909308,-0.655747,-0.672278,0.609908,-0.608988,-0.319946,-0.677765,-0.722143,-0.440620,-0.807766,-0.719734,-0.715493,-0.855289,-0.765221,-0.464594,-0.482679,-0.539556,-0.340218,-0.333127,-0.326587,-0.333127,-0.334711,-0.334394,2.977818,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571
2919,-0.555106,-0.445987,0.091170,-0.094877,0.435084,-1.355623,-0.194134,-0.742149,-0.394835,1.102267,1.379462,-0.924886,0.861683,-0.27126,-0.26046,-0.058091,0.019327,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.676684,0.337435,0.947826,-1.253329,0.925333,-1.372501,-1.463519,0.609908,-1.093666,0.730468,-1.534502,-0.998537,-1.309204,-1.307747,-1.314106,-1.483752,-1.585401,-1.635000,-0.915273,-1.259291,-1.162742,-0.340218,3.001856,-0.326587,-0.333127,-0.334711,-0.334394,-0.335816,-0.338493,-0.340218,-0.316213,-0.212111,-0.247237,-0.128232,-0.21648,-0.246261,-0.167274,-0.194533,-0.206091,-0.205413,-0.205187,-0.198294,-0.204051,-0.194296,-0.210342,-0.209898,5.153081,-0.203368,-0.198060,-0.206316,-0.223325,-0.219497,-0.236532,-0.143275,-0.238542,-0.150571

In [32]:
# importing libraries
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler

In [33]:
# split the data
X_train = train_final
y_train = target
X_test = test_final

In [34]:
# scaling the inputs
scaler = StandardScaler()
scaled_X = scaler.fit_transform(data5)

In [35]:
# training model with 0.5 alpha value
model = Ridge(alpha = 0.5, normalize = False, tol = 0.001, \
              solver ='auto', random_state = 42)
model.fit(X_train, y_train)

Ridge(alpha=0.5, random_state=42)

In [36]:
# predicting the y_test
y_pred = model.predict(X_test)

In [38]:
prediction_df = pd.DataFrame({"time": test_time, "load_shortfall_3h":y_pred}).set_index('time')
prediction_df

                     load_shortfall_3h
time
2018-01-01 00:00:00       10014.248612
2018-01-01 03:00:00        9070.374296
2018-01-01 06:00:00       10328.047054
2018-01-01 09:00:00       10096.411960
2018-01-01 12:00:00       10152.377431
...                                ...
2018-12-31 09:00:00        9110.137330
2018-12-31 12:00:00       11850.104978
2018-12-31 15:00:00       13200.011062
2018-12-31 18:00:00       12339.359811
2018-12-31 21:00:00       10046.312976

[2920 rows x 1 columns]

In [39]:
res = prediction_df.to_csv('ridge_model.csv')

In [ ]:
# models that did not perform
# Decision tree